name: luckyfit_90
description: LuckyFit 90 - Transform Yourself in 90 Days, fully offline Flutter fitness app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.68.0
  lottie: ^3.1.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_local_notifications: ^17.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/svg/
