import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/app_state_provider.dart';
import '../services/fitness_repository.dart';
import '../utils/extensions.dart';
import '../widgets/circular_progress_widget.dart';
import '../widgets/custom_app_bar.dart';
import '../widgets/progress_chart.dart';
import '../widgets/stat_card.dart';
class HomeScreen extends StatelessWidget { const HomeScreen({super.key}); @override Widget build(BuildContext context) { final app = context.watch<AppStateProvider>(); final meals = FitnessRepository().meals(); final workout = FitnessRepository().workouts()[DateTime.now().weekday - 1]; return Scaffold(appBar: const CustomAppBar(title: 'Good Morning', subtitle: 'Transform Yourself in 90 Days'), body: ListView(padding: context.pagePadding, children: [LayoutBuilder(builder: (context, c) { final wide = c.maxWidth > 680; final cards = [StatCard(title: 'Current Weight', value: '${app.profile.currentWeightKg.compact(' kg')}', icon: Icons.monitor_weight, footer: 'Goal ${app.profile.goalWeightKg.compact(' kg')}'), StatCard(title: 'BMI', value: app.bmi.toStringAsFixed(1), icon: Icons.calculate, footer: 'BMR ${app.bmr.toStringAsFixed(0)} kcal'), StatCard(title: 'Calories', value: '${app.calories}', icon: Icons.local_fire_department, footer: 'Protein ${app.protein.toStringAsFixed(0)}g'), StatCard(title: 'Water', value: '${app.waterGlasses}/8', icon: Icons.water_drop, footer: 'Workout streak ${app.workoutStreak} days')]; return GridView.count(crossAxisCount: wide ? 4 : 2, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), childAspectRatio: wide ? 1.25 : 1.05, children: cards); }), const SizedBox(height: 12), Card(child: ListTile(title: Text('Today\'s Workout: ${workout.title}'), subtitle: Text(workout.day), leading: const Icon(Icons.fitness_center, color: Colors.amber))), Card(child: ListTile(title: const Text('Today\'s Meals'), subtitle: Text(meals.map((m) => m.name).join(' • ')), leading: const Icon(Icons.restaurant, color: Colors.amber))), Row(mainAxisAlignment: MainAxisAlignment.spaceAround, children: [CircularProgressWidget(percent: app.completedWorkouts.length / 4, label: 'Workout', center: '${(app.completedWorkouts.length / 4 * 100).clamp(0, 100).round()}%'), CircularProgressWidget(percent: app.waterGlasses / 8, label: 'Hydration', center: '${app.waterGlasses}/8')]), const SizedBox(height: 12), const Text('Weekly Progress Chart', style: TextStyle(fontWeight: FontWeight.bold)), ProgressChart(entries: app.history), Card(child: Padding(padding: const EdgeInsets.all(18), child: Text('“${app.quote}”', textAlign: TextAlign.center, style: const TextStyle(fontSize: 16, fontStyle: FontStyle.italic))))])); } }
