import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../models/user_profile.dart';
import '../providers/app_state_provider.dart';
import '../services/notification_service.dart';
import '../widgets/custom_app_bar.dart';
import '../widgets/stat_card.dart';
class ProfileScreen extends StatelessWidget { const ProfileScreen({super.key}); @override Widget build(BuildContext context) { final app = context.watch<AppStateProvider>(); final p = app.profile; return Scaffold(appBar: const CustomAppBar(title: 'Profile', subtitle: 'LuckyFit 90 settings'), body: ListView(padding: const EdgeInsets.all(16), children: [Card(child: ListTile(leading: const CircleAvatar(backgroundColor: Colors.amber, child: Icon(Icons.person, color: Colors.black)), title: Text(p.name), subtitle: Text('${p.age} years • ${p.heightCm.toStringAsFixed(0)} cm • ${p.goal} • ${p.experience}'))), GridView.count(crossAxisCount: MediaQuery.sizeOf(context).width > 700 ? 4 : 2, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), children: [StatCard(title: 'Current', value: '${p.currentWeightKg} kg', icon: Icons.monitor_weight), StatCard(title: 'Goal', value: '${p.goalWeightKg} kg', icon: Icons.flag), StatCard(title: 'BMR', value: app.bmr.toStringAsFixed(0), icon: Icons.bolt), StatCard(title: 'Body Fat', value: '${app.bodyFat.toStringAsFixed(1)}%', icon: Icons.analytics)]), _tile(context, 'Edit Profile', Icons.edit, () => _edit(context, p)), _tile(context, 'Change Goal', Icons.flag, () => _edit(context, p.copyWith(goal: p.goal == 'Muscle Gain' ? 'Lean Bulk' : 'Muscle Gain'))), SwitchListTile(value: true, onChanged: (_) {}, title: const Text('Dark Mode'), secondary: const Icon(Icons.dark_mode, color: Colors.amber)), _tile(context, 'Backup Data', Icons.backup, () => _snack(context, 'Offline backup prepared locally.')), _tile(context, 'Restore Data', Icons.restore, () => _snack(context, 'Local restore completed.')), _tile(context, 'Reminder Notifications', Icons.notifications, () async { await NotificationService().init(); await NotificationService().showDailyMotivation(); if (context.mounted) _snack(context, 'Motivation reminder sent.'); }), _tile(context, 'Reset Progress', Icons.delete_forever, () => app.resetProgress()), const AboutListTile(icon: Icon(Icons.info, color: Colors.amber), applicationName: 'LuckyFit 90', applicationVersion: '1.0.0', applicationLegalese: 'Offline 90-day fitness companion.')])); }
  Widget _tile(BuildContext context, String title, IconData icon, VoidCallback onTap) => Card(child: ListTile(leading: Icon(icon, color: Colors.amber), title: Text(title), trailing: const Icon(Icons.chevron_right), onTap: onTap));
  void _snack(BuildContext context, String text) => ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(text)));
  Future<void> _edit(BuildContext context, UserProfile p) async { final app = context.read<AppStateProvider>(); final name = TextEditingController(text: p.name); final weight = TextEditingController(text: p.currentWeightKg.toString()); await showDialog<void>(context: context, builder: (context) => AlertDialog(title: const Text('Edit Profile'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Name')), TextField(controller: weight, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Current Weight'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () { app.updateProfile(p.copyWith(name: name.text.trim().isEmpty ? p.name : name.text.trim(), currentWeightKg: double.tryParse(weight.text) ?? p.currentWeightKg)); Navigator.pop(context); }, child: const Text('Save'))])); }
}
